language: ruby
cache: bundler
sudo: false

rvm:
- 2.0.0
- 2.1
- 2.2

branches:
  only:
    - master

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "YViCAUlIVPpsCmzHYk4V0tJ2+WOXdzwypNFDSJTCclUPdI1VTovwv+tJ//+HmNuUGbdo7ouvgF2Cv0i87R5E7KPcqkFAjt+i8PIMgEF4tzXB4tX6j8uD4T1MDjBr/JKxC/DEifY7OlVfQdwYDj669jtGkPARYOo7DCt4/+eHtbCt2SskDJqksU0UY58e+CMjKKXxQOtETA/YdOI1iInsqMSbbVRBWelvJfd5pLzHE4g8qFLxFXjioAca+ScY4pqjfFHrNOqyQL/DvfQ4BAboUujFnbRcdU0NimRlh4nIr7d9uGhoXkJbox/XRPQtUYlIP+aguzrrlsjlA10cTA3QU1+1kXEInhf75hXmJ1agy2cYXVsKmGhWXktTl9TulEzLiUJyWjMnskxOKq6hjS0pSmVLicRYUcI4P6c67FF2OU28y/6Ndxggq2qFPtal22wQ/Y1Qgzu7AkkU1+EynqeFmE21G9iMkTC5Nr0yZ7PyHgwrkQXmSYVHw+WkPQibovGJZZZCeyOuFSa0f/OmD9dtBVHIFYKoN7W2iQf9HR4/fgnKpEzfb78b4d3S0MXsV2hdawle8zjooRK2IsRDAtakV+u9jCgQP7a9hPMBQKrQHCInRRRzenANIEK6z/HID4BfotV5YV+c25Qzp+I6iPHQgVbsU+R0gmCRiMxXlG2oV80="
